export const wilayas=[
    {"name":"Alger", "code":"16"},
    {"name":"Blida","code":"09"},
    {"name":"Chlef","code":"02"},
    {"name":"Alger", "code":"16"},
    {"name":"Blida","code":"09"},
    {"name":"Chlef","code":"02"},
    {"name":"Alger", "code":"16"},
    {"name":"Blida","code":"09"},
    {"name":"Chlef","code":"02"},
    {"name":"Alger", "code":"16"},
    {"name":"Blida","code":"09"},
    {"name":"Chlef","code":"02"},
    {"name":"Alger", "code":"16"},
    {"name":"Blida","code":"09"},
    {"name":"Chlef","code":"02"},
    {"name":"Alger", "code":"16"},
    {"name":"Blida","code":"09"},
    {"name":"Chlef","code":"02"},
    {"name":"Alger", "code":"16"},
    {"name":"Blida","code":"09"},
    {"name":"Chlef","code":"02"},
    {"name":"Alger", "code":"16"},
    {"name":"Blida","code":"09"},
    {"name":"Chlef","code":"02"},
]